### ISSUE TITLE
ImportErro BuildEventHuddling 

### ISSUE THREAD

**Issue by sommerc** [fdechaumont/lmt-analysis#3]
Hi Fabrice,

the BuildEventHuddling doesn't seem to exist in the repo. 

```
  File "Rebuild_All_Event.py", line 12, in <module>
    from lmtanalysis import BuildEventTrain3, BuildEventTrain4, BuildEventTrain2, BuildEventFollowZone, BuildEventRear5, BuildEventFloorSniffing,\
ImportError: cannot import name 'BuildEventHuddling'
```

After commenting the import it works fine.

**Comment by fdechaumont** [comment]
Hi Christoph,

Thanks for reporting,
Actually this import is not used in this file, so I just released a version where I removed it from the import section.

Still, I am surprised the import did not work as the file is here:
https://github.com/fdechaumont/lmt-analysis/blob/master/LMT/lmtanalysis/BuildEventHuddling.py

Could you tell me what dev tools do you use, so that I can check compatibility of the code ?

Thanks.

Fabrice

**Comment by sommerc** [comment]
the ImportError came when executing "Rebuild_All_Event.py"

**Comment by fdechaumont** [comment]
Ok, the import was useless and is now removed :)
